// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using New_ATCSharp.Data;

#nullable disable

namespace New_ATCSharp.Migrations
{
    [DbContext(typeof(New_ATCSharpContext))]
    partial class New_ATCSharpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("New_ATCSharp.Models.CarroViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarImgFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Potencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CarroViewModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarImgFileName = "skylinevelozesefuriosos.jpeg",
                            Cor = "Azul e prata",
                            Marca = "Nissan",
                            Modelo = "Skyline",
                            Potencia = 100
                        },
                        new
                        {
                            Id = 2,
                            CarImgFileName = "toyota-supra.jpg",
                            Cor = "Laranja",
                            Marca = "Toyota",
                            Modelo = "Supra",
                            Potencia = 200
                        });
                });

            modelBuilder.Entity("New_ATCSharp.Models.PilotoViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorridasGanhas")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Equipe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PilotoViewModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorridasGanhas = 100,
                            Data = new DateTime(2023, 12, 16, 0, 37, 47, 839, DateTimeKind.Local).AddTicks(2749),
                            Equipe = "velozes e furiosos",
                            Idade = 52,
                            Nome = "Dominic Toreto"
                        },
                        new
                        {
                            Id = 2,
                            CorridasGanhas = 85,
                            Data = new DateTime(2023, 12, 16, 0, 37, 47, 839, DateTimeKind.Local).AddTicks(2758),
                            Equipe = "velozes e furiosos",
                            Idade = 43,
                            Nome = "Brian O´Conner"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
